### ISSUE TITLE
Packages depending on augment cannot be installed with pip

### ISSUE THREAD

**Issue by clbarnes** [funkey/augment#1]
The recommended way to install packages, even from github or locally, is now to use `pip`, like `pip install git+https://github.com/name/repo` or `pip install .`. In pip, `dependency_links` are only followed with the `--process-dependency-links` option (which is deprecated but not going away any time soon).

However, even with that option, pip ignores `dependency_links` if there is a package of the same name on PyPI, and unfortunately, there exists [this package](https://pypi.python.org/pypi/Augment/0.4) which hasn't seen a meaningful update since 2011.

This means that no package depending on augment can itself be installed with pip; it must use a direct call to `setup.py`. This means you can't use extras (e.g. I was trying to set up a tensorflow extra for gunpowder), develop/editable installs are tricky, and it's harder to use tools like `tox`.

One gross but viable workaround is to do 

```python
import subprocess
import shlex

args = shlex.split("pip install git+https://github.com/funkey/augment")
subprocess.run(args)
# subprocess.call(args)  # in python <3.5
```

in the downstream package' setup.py and remove it from install_requires. This would need to be documented.

**Comment by hanslovsky** [comment]
I tried to install `gunpowder` from my local git clone via `pip install --user .`. Unfortunately, pip does not respect the workaraound to `augment`, so I have to do that manually, which is ok, but took me some time to figure out.
It would probably be advisable to rename the `augment` package, to something more specific/meaningful, like `augment_ndarray` or similar, which could then be added to pypi. The changes downstream would be minimal as you could replace `import augment` by `import augmend_ndarray as augment`.

**Comment by clbarnes** [comment]
Agreed, this was always a hacky workaround. It just feels wrong to raise PRs to tell developers to change their libraries' names ;)

You wouldn't even need to make any downstream changes, because the package name on PyPI does not need to be the same as the module name to be imported (it's just good practice for them to be the same and certainly needs to be documented heavily if not). `import augment` could stay as it is, so long as you don't mind clashing with the existing augment (which hasn't been meaningfully updated in 7 years) in downstream users' environments - I think that's fine. Given that nobody installs (this) `augment` from PyPI right now, using a non-"augment" package name on PyPI breaks no workflows.

P.S. updating the workaround in the OP for documentation purposes.

**Comment by hanslovsky** [comment]
I wasn't aware that the package on PyPI could have a different name. Is that determined by the `name` parameter in `setuptools.setup`?

**Comment by clbarnes** [comment]
I believe so. https://the-hitchhikers-guide-to-packaging.readthedocs.io/en/latest/quickstart.html#describe-your-project

The `"packages"` field lists which packages are actually installed, and if it's not obvious where they are, `"package_dirs"` contains that mapping. This is why I have to look up the [beautifulsoup](https://www.crummy.com/software/BeautifulSoup/bs4/doc/#installing-beautiful-soup) docs every time I install or import it <_<

It's mainly useful for disambiguating package names if you're forking an existing project and want it to remain a drop-in replacement.

This is also how `pip install one_package` can install multiple top-level python modules.

**Comment by funkey** [comment]
I think no one uses `augment` outside of `gunpowder`. How about we just merge it in there?

**Comment by hanslovsky** [comment]
Works for me.

**Comment by clbarnes** [comment]
I'm generally in favour of modularity, but if you think augment is too specific to be useful to anyone not already using gunpowder, go ahead!

**Comment by hanslovsky** [comment]
You can add this to install_requires:
```python
install_requires = [
    ...
    'augment @ git+https://github.com/funkey/augment',
    ...
]
```

cf funkey/gunpowder#38

**Comment by hanslovsky** [comment]
I stand correct, git repositories inside `install_requires` are not a viable solution:
```sh
$ pip install fuse
Collecting fuse
  Using cached https://files.pythonhosted.org/packages/55/a1/3e9dff172d9918d4562f0acf73024cf502163febc4c1873db5967e8b2855/fuse-0.1.0.tar.gz
Packages installed from PyPI cannot depend on packages which are not also hosted on PyPI.
fuse depends on augment@ git+https://github.com/funkey/augment@4a42b01ccad7607b47a1096e904220729dbcb80a 
```

The only solution is to rename augment or to integrate it into gunpowder. Otherwise no downstream packages can be made available through pypi. This should probably happen before the gunpowder-1.0 release.

**Comment by clbarnes** [comment]
Strictly speaking, the fact that (this) `augment` isn't on PyPI means that gunpowder will always be dependent on the hack I posted above (which should be avoided if possible). So all that would need to happen would be for `augment` to be put on PyPI, with its `name` field in the setup.py as pyaugment, or imgaugment or whatever. It would still be importable as `augment`, so it wouldn't change any downstream code - that downstream code already doesn't use normal dependency systems to install it for all the reasons detailed here.

So really this issue just boils down to "put this on PyPI" :smiley: 

I think this library has merit outside of gunpowder as a light, low-dependency alternative to the array augmentations bundled in larger libraries, so would prefer that to adding complexity to gunpowder.

**Comment by funkey** [comment]
Thanks to @clbarnes, `augment` is now on [PyPI](https://pypi.org/project/augment-nd/), named `augment-nd`.
